# -*- coding: utf-8 -*-

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - pip install --upgrade pip  --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install .

script:
  - coverage run --source=fixture setup.py test

after_success:
  - coveralls

notifications:
  email: false
